/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Unity Fan youtube channel (https://sketchfab.com/unityfan777)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/free-sci-fi-city-public-domain-cc0-b353532235bb4c45afeac578187c9be1
Title: FREE Sci-Fi City - public domain (CC0)
*/

import React, { useRef, useMemo, useContext, createContext } from "react"
import { useGLTF, Merged } from "@react-three/drei"
//import {useFrame, useThree} from '@react-three/fiber'
//import { Instance } from '@react-three/fiber/dist/declarations/src/core/renderer'
import {a} from '@react-spring/three'

import islandScene from '../assets/sci-fi-island.glb'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Unity Fan youtube channel (https://sketchfab.com/unityfan777)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/free-sci-fi-city-public-domain-cc0-b353532235bb4c45afeac578187c9be1
Title: FREE Sci-Fi City - public domain (CC0)
*/

const Island = (props) => {
    const islandRef = useRef()
  const { nodes, materials } = useGLTF(
    islandScene
  );
  return (
    <a.group ref={islandRef} {...props}>
      <group scale={0.01}>
        <group
          position={[-3108.8078613, -320.712616, 900.1256104]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building001_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building001_metal1_0.geometry}
            material={materials.metal1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building001_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building001_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
        </group>
        <group
          position={[-3715.4255371, 1213.8901367, -400.5231934]}
          rotation={[-Math.PI / 2, -2e-7, Math.PI / 2]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building002_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building002_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building002_metal3_0.geometry}
            material={materials.metal3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building002_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
        </group>
        <group
          position={[-4381.1235352, 0, 332.0497437]}
          rotation={[-Math.PI / 2, 1e-7, -Math.PI / 4]}
          scale={[100.0000076, 100.0000076, 100]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building006_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building006_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building006_metal3_0.geometry}
            material={materials.metal3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building006_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
        </group>
        <group
          position={[-3182.8515625, -219.0818481, -702.418335]}
          rotation={[-Math.PI / 2, 1e-7, 2.3561943]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building007_metal1_0.geometry}
            material={materials.metal1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building007_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building007_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building007_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
        </group>
        <group
          position={[-4810.3896484, 0, -711.6213379]}
          rotation={[-Math.PI / 2, -2e-7, Math.PI / 2]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building011_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building011_metal3_0.geometry}
            material={materials.metal3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building011_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building011_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
        </group>
        <group
          position={[-4808.6445313, 873.3230591, -714.7470703]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building012_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building012_metal3_0.geometry}
            material={materials.metal3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building012_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
        </group>
        <group
          position={[-3929.7490234, 0, 208.3443604]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building013_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building013_metal4_0.geometry}
            material={materials.metal4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building013_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building013_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
        </group>
        <group
          position={[-6234.8818359, 0, -406.8812866]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building015_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building015_metal3_0.geometry}
            material={materials.metal3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building015_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building015_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
        </group>
        <group
          position={[-4847.3833008, -4e-7, 651.7300415]}
          rotation={[-Math.PI / 2, 1e-7, -Math.PI / 4]}
          scale={[100.0000076, 100.0000076, 100]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building017_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building017_metal3_0.geometry}
            material={materials.metal3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building017_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building017_windows_lit4_0.geometry}
            material={materials.windows_lit4}
          />
        </group>
        <group
          position={[-3726.3232422, -163.5008698, -1322.1934814]}
          rotation={[-Math.PI / 2, 0, 2e-7]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building018_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building018_metal1_0.geometry}
            material={materials.metal1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building018_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building018_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
        </group>
        <group
          position={[-4426.6767578, 0, -363.6834717]}
          rotation={[-Math.PI / 2, -2e-7, Math.PI / 2]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building019_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building019_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building019_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building019_metal3_0.geometry}
            material={materials.metal3}
          />
        </group>
        <group
          position={[-3718.5512695, 0, -402.268158]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building020_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building020_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building020_metal3_0.geometry}
            material={materials.metal3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building020_dark_0.geometry}
            material={materials.dark}
          />
        </group>
        <group
          position={[-3600, 0, 400]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building021_metal3_0.geometry}
            material={materials.metal3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building021_windows_lit4_0.geometry}
            material={materials.windows_lit4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building021_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building021_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
        </group>
        <group
          position={[-4362.3383789, 1e-7, 823.6112671]}
          rotation={[-Math.PI / 2, -1e-7, Math.PI / 4]}
          scale={[100.0000076, 100.0000076, 100]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building022_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building022_metal1_0.geometry}
            material={materials.metal1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building022_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building022_windows_lit2_0.geometry}
            material={materials.windows_lit2}
          />
        </group>
        <group
          position={[-5591.3911133, 0, -377.0091553]}
          rotation={[-Math.PI / 2, -1e-7, Math.PI / 4]}
          scale={[100.0000076, 100.0000076, 100]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building023_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building023_metal1_0.geometry}
            material={materials.metal1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building023_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building023_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
        </group>
        <group
          position={[-3898.3039551, -6e-7, 885.1884766]}
          rotation={[-Math.PI / 2, -2e-7, Math.PI / 2]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building025_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building025_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building025_metal4_0.geometry}
            material={materials.metal4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building025_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
        </group>
        <group
          position={[-4380.1474609, 1213.8901367, 335.4938965]}
          rotation={[-Math.PI / 2, -1e-7, Math.PI / 4]}
          scale={[100.0000076, 100.0000076, 100]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building026_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building026_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building026_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building026_metal3_0.geometry}
            material={materials.metal3}
          />
        </group>
        <group
          position={[-5173.7958984, 0.000003, -975.7335815]}
          rotation={[-Math.PI / 2, -1e-7, Math.PI / 4]}
          scale={[100.0000076, 100.0000076, 100]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building027_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building027_metal3_0.geometry}
            material={materials.metal3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building027_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building027_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
        </group>
        <group
          position={[-5370.5229492, 0, 965.704834]}
          rotation={[-Math.PI / 2, 1e-7, 2.3561943]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building028_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building028_metal1_0.geometry}
            material={materials.metal1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building028_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building028_windows_lit2_0.geometry}
            material={materials.windows_lit2}
          />
        </group>
        <group
          position={[-4726.5556641, 0, -19.9059906]}
          rotation={[-Math.PI / 2, 1e-7, 2.3561943]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building029_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building029_metal1_0.geometry}
            material={materials.metal1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building029_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building029_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
        </group>
        <group
          position={[-2918.4311523, -115.5947952, 123.5136032]}
          rotation={[-Math.PI / 2, -2e-7, Math.PI / 2]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building030_metal1_0.geometry}
            material={materials.metal1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building030_windows_lit2_0.geometry}
            material={materials.windows_lit2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building030_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building030_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
        </group>
        <group
          position={[-3335.8908691, 0, -27.6607513]}
          rotation={[-Math.PI / 2, -1e-7, Math.PI / 4]}
          scale={[100.0000076, 100.0000076, 100]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building031_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building031_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building031_metal4_0.geometry}
            material={materials.metal4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building031_dark_0.geometry}
            material={materials.dark}
          />
        </group>
        <group
          position={[-3541.2753906, 0.0000015, 1328.3887939]}
          rotation={[-Math.PI / 2, -1e-7, Math.PI / 4]}
          scale={[100.0000076, 100.0000076, 100]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building032_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building032_windows_lit4_0.geometry}
            material={materials.windows_lit4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building032_metal3_0.geometry}
            material={materials.metal3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building032_dark_0.geometry}
            material={materials.dark}
          />
        </group>
        <group
          position={[-4364.362793, 0, 1696.5739746]}
          rotation={[-Math.PI / 2, 0, -2.3561943]}
          scale={[99.9999924, 99.9999924, 100]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building033_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building033_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building033_metal1_0.geometry}
            material={materials.metal1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building033_dark_0.geometry}
            material={materials.dark}
          />
        </group>
        <group
          position={[-4226.4487305, 0, -830.1725464]}
          rotation={[-Math.PI / 2, -2e-7, Math.PI / 2]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building034_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building034_windows_lit4_0.geometry}
            material={materials.windows_lit4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building034_metal3_0.geometry}
            material={materials.metal3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building034_dark_0.geometry}
            material={materials.dark}
          />
        </group>
        <group
          position={[-4626.4487305, 0, -1247.871582]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building009_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building009_windows_lit2_0.geometry}
            material={materials.windows_lit2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building009_metal1_0.geometry}
            material={materials.metal1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building009_dark_0.geometry}
            material={materials.dark}
          />
        </group>
        <group
          position={[-5089.0458984, 0, -339.4307251]}
          rotation={[-Math.PI / 2, -1e-7, Math.PI / 4]}
          scale={[100.0000076, 100.0000076, 100]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building014_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building014_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building014_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building014_metal3_0.geometry}
            material={materials.metal3}
          />
        </group>
        <group
          position={[-5170.3510742, 1213.8901367, -976.7097168]}
          rotation={[-Math.PI / 2, 1e-7, 2.3561943]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building024_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building024_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building024_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building024_metal3_0.geometry}
            material={materials.metal3}
          />
        </group>
        <group
          position={[-4944.0551758, 0, 1702.111084]}
          rotation={[-Math.PI / 2, 1e-7, -Math.PI / 4]}
          scale={[100.0000076, 100.0000076, 100]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building035_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building035_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building035_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building035_metal3_0.geometry}
            material={materials.metal3}
          />
        </group>
        <group
          position={[-5250.5205078, 0, 1380.2956543]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building008_metal4_0.geometry}
            material={materials.metal4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building008_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building008_dark_0.geometry}
            material={materials.dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building008_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
        </group>
        <group
          position={[-4800.3232422, 0, 1158.6899414]}
          rotation={[-Math.PI / 2, 1e-7, 2.3561943]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building_metal3_0.geometry}
            material={materials.metal3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building_dark_0.geometry}
            material={materials.dark}
          />
        </group>
        <group
          position={[-5355.2734375, 0, 306.2279663]}
          rotation={[-Math.PI / 2, -2e-7, Math.PI / 2]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building004_windows_unlit_0.geometry}
            material={materials.windows_unlit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building004_windows_lit1_0.geometry}
            material={materials.windows_lit1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building004_metal1_0.geometry}
            material={materials.metal1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.building004_dark_0.geometry}
            material={materials.dark}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud012_cloud_0.geometry}
          material={materials.cloud}
          position={[-2524.3068848, -314.2801208, 2326.3706055]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1061.9085693}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud019_cloud_0.geometry}
          material={materials.cloud}
          position={[-3350.5595703, -137.6887512, -1245.0787354]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1198.487915}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud010_cloud_0.geometry}
          material={materials.cloud}
          position={[-2712.9055176, -137.6887512, -1245.0787354]}
          rotation={[0, Math.PI / 2, 0]}
          scale={828.8737183}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud011_cloud_0.geometry}
          material={materials.cloud}
          position={[-2504.0446777, -137.6887512, 1231.4688721]}
          rotation={[0, Math.PI / 2, 0]}
          scale={828.8737183}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud013_cloud_0.geometry}
          material={materials.cloud}
          position={[-2578.6845703, -68.9167023, 352.1422424]}
          rotation={[0, Math.PI / 2, 0]}
          scale={584.9835205}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud014_cloud_0.geometry}
          material={materials.cloud}
          position={[-5763.7163086, -137.6887512, -1245.0787354]}
          rotation={[0, Math.PI / 2, 0]}
          scale={2332.5957031}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud_cloud_0.geometry}
          material={materials.cloud}
          position={[-2581.8596191, -137.6887512, -840.4188232]}
          rotation={[0, Math.PI / 2, 0]}
          scale={463.2510681}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud001_cloud_0.geometry}
          material={materials.cloud}
          position={[-2691.8178711, -137.6887512, 0.0000954]}
          rotation={[0, Math.PI / 2, 0]}
          scale={828.8737183}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud003_cloud_0.geometry}
          material={materials.cloud}
          position={[-3001.9782715, -137.6887512, -950.0819092]}
          rotation={[0, Math.PI / 2, 0]}
          scale={828.8737183}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud004_cloud_0.geometry}
          material={materials.cloud}
          position={[-3001.9782715, -137.6887512, 972.9157715]}
          rotation={[0, Math.PI / 2, 0]}
          scale={828.8737183}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud006_cloud_0.geometry}
          material={materials.cloud}
          position={[-3753.9082031, -141.373291, 1921.2093506]}
          rotation={[0, Math.PI / 2, 0]}
          scale={914.3898926}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud005_cloud_0.geometry}
          material={materials.cloud}
          position={[-3999.3271484, -16.452837, 1990.463623]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1086.2054443}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud023_cloud_0.geometry}
          material={materials.cloud}
          position={[-7213.559082, -137.6887512, 2045.3552246]}
          rotation={[0, Math.PI / 2, 0]}
          scale={2332.5957031}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud024_cloud_0.geometry}
          material={materials.cloud}
          position={[-6715.074707, -137.6887512, 2045.3552246]}
          rotation={[0, Math.PI / 2, 0]}
          scale={828.8737183}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud025_cloud_0.geometry}
          material={materials.cloud}
          position={[-6318.8251953, -137.6887512, 2126.9360352]}
          rotation={[0, Math.PI / 2, 0]}
          scale={978.1818237}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud029_cloud_0.geometry}
          material={materials.cloud}
          position={[-6548.1367188, -137.6887512, 285.6983032]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1473.8894043}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud009_cloud_0.geometry}
          material={materials.cloud}
          position={[-4791.6245117, 299.2146912, 1921.2093506]}
          rotation={[0, Math.PI / 2, 0]}
          scale={914.3898926}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud026_cloud_0.geometry}
          material={materials.cloud}
          position={[-5156.5654297, -137.6887512, 2143.7702637]}
          rotation={[0, Math.PI / 2, 0]}
          scale={781.4871216}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud027_cloud_0.geometry}
          material={materials.cloud}
          position={[-5698.3349609, -137.6887512, 1324.3453369]}
          rotation={[0, Math.PI / 2, 0]}
          scale={978.1818237}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud008_cloud_0.geometry}
          material={materials.cloud}
          position={[-4840.6518555, -137.6887512, 972.9157715]}
          rotation={[0, Math.PI / 2, 0]}
          scale={828.8737183}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud016_cloud_0.geometry}
          material={materials.cloud}
          position={[-3626.3466797, -137.6887512, 1231.4688721]}
          rotation={[0, Math.PI / 2, 0]}
          scale={828.8737183}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud028_cloud_0.geometry}
          material={materials.cloud}
          position={[-6177.1914063, -137.6887512, 582.4545898]}
          rotation={[0, Math.PI / 2, 0]}
          scale={978.1818237}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud002_cloud_0.geometry}
          material={materials.cloud}
          position={[-4080.1208496, 308.6864929, -368.2739563]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1452.8457031}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud017_cloud_0.geometry}
          material={materials.cloud}
          position={[-3454.9589844, -49.3770142, 162.0721741]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1061.9085693}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud021_cloud_0.geometry}
          material={materials.cloud}
          position={[-6103.2177734, -137.6887512, -1163.4976807]}
          rotation={[0, Math.PI / 2, 0]}
          scale={978.1818237}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud007_cloud_0.geometry}
          material={materials.cloud}
          position={[-4530.4912109, -137.6887512, 0.0000954]}
          rotation={[0, Math.PI / 2, 0]}
          scale={828.8737183}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud015_cloud_0.geometry}
          material={materials.cloud}
          position={[-3814.1196289, -137.6887512, -1245.0787354]}
          rotation={[0, Math.PI / 2, 0]}
          scale={828.8737183}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud018_cloud_0.geometry}
          material={materials.cloud}
          position={[-3700.9865723, -432.6370239, 352.1422424]}
          rotation={[0, Math.PI / 2, 0]}
          scale={584.9835205}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud020_cloud_0.geometry}
          material={materials.cloud}
          position={[-6499.4682617, -137.6887512, -1245.0787354]}
          rotation={[0, Math.PI / 2, 0]}
          scale={828.8737183}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud022_cloud_0.geometry}
          material={materials.cloud}
          position={[-5217.4814453, -137.6887512, -1955.9990234]}
          rotation={[0, Math.PI / 2, 0]}
          scale={781.4871216}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stars001_stars_0.geometry}
          material={materials.stars}
          position={[-4776.1152344, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={124.9263535}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stars_stars_0.geometry}
          material={materials.stars}
          position={[-4776.1152344, 1568.6437988, 0]}
          rotation={[-1.6980751, 0.1164695, 0.4565521]}
          scale={[130.8900909, 130.8900757, 130.8901062]}
        />
      </group>
    </a.group>
  );
}

export default Island
